# version: "3.8"
# services:
#   db:
#     image: postgres
#     container_name: local_pgdb
#     restart: always
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: root
#       POSTGRES_PASSWORD: password
#     volumes:
#       - local_pgdata:/var/lib/postgresql/data
#     networks:
#       - dockernet

#   pgadmin:
#     image: dpage/pgadmin4
#     container_name: pgadmin4_container
#     restart: always
#     ports:
#       - "8080:80"
#     environment:
#       PGADMIN_DEFAULT_EMAIL: root@gmail.com
#       PGADMIN_DEFAULT_PASSWORD: password
#     volumes:
#       - pgadmin-data:/var/lib/pgadmin
#     networks:
#       - dockernet

# volumes:
#   local_pgdata:
#   pgadmin-data:

# networks:
#   dockernet:
#     external: true

version: "3.1"
services:
  odoo:
    image: odoo:17.0
    ports:
      - "1877:8069"
    command: ["--log-level=debug"]
    container_name: "odoo17_technical"
    restart: "unless-stopped"
    volumes:
      - ./conf:/etc/odoo
      - ./addons:/mnt/extra-addons

    networks:
      - dockernet

networks:
  dockernet:
    name: dockernet
    external: true
